#!/bin/sh


if ! &>/dev/null command git -v 
then
  1>&2 printf 'git is required!\n'
  exit 1
fi

git clone \
    --quiet \
    --single-branch \
    --recurse-submodules \
    --branch 'jak0b/chore/feat/add-experimental-clone-scripts' \
    https://github.com/jak0b/dot.git '/tmp/dot'
