#!/bin/zsh

if [[ -n $XDG_CONFIG_HOME ]];
then # should be set on Linux
  CONF_DIR="$XDG_CONFIG_HOME"
else # used in Darwin or oter BSDs
  CONF_DIR="$HOME/.config"
fi

DOT_DIR="${CONF_DIR}/dot"

function point() {
  local dst="$1" link="$2"

  if [[ -L $link ]]
  then
    if [[ $(readlink "$link") == $dst ]]
    then
      printf 'link "%s" -> "%s" already exist\n' "$link" "$dst"
      return 
    else
      printf 'link "%s" -> "%s" is not pointing to expected location - relinking\n' "$link" "$dst" 2>&1
      unlink "$link" && ln -s "$dst" "$link"
      printf 'created link "%s" -> "%s"\n' "$link" "$dst" 2>&1
    fi
  else
    ln -s "$dst" "$link"
    printf 'created link "%s" -> "%s"\n' "$link" "$dst" 2>&1
  fi
}

point "${DOT_DIR}/zsh"                  "${CONF_DIR}/zsh"
point "${CONF_DIR}/zsh/zshrc.zsh"       "$HOME/.zshrc"
point "${DOT_DIR}/wezterm"              "${CONF_DIR}/wezterm"
point "${DOT_DIR}/htop"                 "${CONF_DIR}/htop"
point "${DOT_DIR}/nvim"                 "${CONF_DIR}/nvim"
